#!/bin/bash

. adb_lib

select_device

screen_path="/sdcard/screen.png"
save_path="/home/artemiy/Загрузки/screens/"
adb -s "$device_id" shell screencap -p /sdcard/screen.png

if [ ! -d "$save_path" ]; then
    mkdir "$save_path"
fi

echo "Enter screen name:"
read name

adb -s "$device_id" pull "$screen_path" -p "$save_path$name.png"
adb -s "$device_id" shell rm "$screen_path"

