#!/bin/bash

rand=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
screen_path="/sdcard/"$rand".png"
name=$(date '+%H:%M:%S')"_"$rand
save_path="/home/artemiy/Загрузки/screens"
devices=$(adb devices | grep -w "device" | awk '{print $1}')

if [ -z "$devices" ]; then
	exit 1
fi

while read device_id
do
    adb </dev/null -s "$device_id" shell screencap -p "$screen_path"
done <<< "$devices"

while read device_id
do
    device_name=$(adb </dev/null -s "$device_id" exec-out getprop "ro.product.model")
    device_path="$save_path/$device_name/$(date '+%Y-%m-%d')/"
    echo "AAAA"
    if [ ! -d "$device_path" ]; then
        mkdir -p "$device_path"
    fi
    adb -s "$device_id" pull "$screen_path" -p "$device_path$name.png"
    adb </dev/null -s "$device_id" shell rm "$screen_path"
done <<< "$devices"
