#!/bin/bash

. adb_lib

select_device

droid_ver=$(adb </dev/null -s "$device_id" exec-out getprop "ro.build.version.release")
device_name=$(adb </dev/null -s "$device_id" exec-out getprop "ro.product.model")

echo "$device_name"', Android '"$droid_ver"
