#!/bin/bash

. adb_lib

select_device

screen_path="/sdcard/screen.png"
save_path="/home/artemiy/Загрузки/screens/"
adb </dev/null -s "$device_id" shell screencap -p "$screen_path"

if [ ! -d "$save_path" ]; then
    mkdir -p "$save_path"
fi

echo "Enter screen name:"
read name

adb -s "$device_id" pull "$screen_path" -p "$save_path$name.png"
adb </dev/null -s "$device_id" shell rm "$screen_path"

