#!/bin/bash

. adb_lib

select_device

#Можно сделать проверку на валидность номера. Находится в пределах от 1 до number_of_devices

select_apk

#Добавить внутри функции проверки наличия, валидности и т.д.

pkg=$(aapt dump badging "$fullpath"|awk -F" " '/package/ {print $2}'|awk -F"'" '/name=/ {print $2}')
package_on_device=$(adb </dev/null -s "$device_id" shell pm list packages | grep "^package:$pkg$")

if [ -n "$package_on_device" ]; then
	echo "Uninstalling <$pkg>, please wait..."
	adb -s "$device_id" -d uninstall "$pkg"
fi

if [ -n "$apk_name" ]; then
	echo "Installing <$apk_name>, please wait..."
	adb -s "$device_id" install -r -d -t "$fullpath"
fi
