#!/bin/bash

. adb_lib

select_device

fullpath=$APK_PATH$1

if [ "$fullpath" = "$APK_PATH" ]; then
	select_apk
fi

if [ ! -f "$fullpath" ]; then
	echo "Selected file $apk does not exist. Press any key to exit"
	read -n 1
	exit 1
fi

pkg=$(aapt dump badging "$fullpath"|awk -F" " '/package/ {print $2}'|awk -F"'" '/name=/ {print $2}')
act=$(aapt dump badging "$fullpath"|awk -F" " '/launchable-activity/ {print $2}'|awk -F"'" '/name=/ {print $2}')
adb -s "$device_id" shell am force-stop $pkg
adb -s "$device_id" shell am start -n $pkg/$act
